import { Artwork } from "interfaces";

export const portfolios: Artwork[] = [
  {title: 'Abook', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'Fint', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'MU', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'Stock', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'My favorite things', type: '그래픽', thumbnail: '', description: ''},
  {title: '믿어줘', type: '영상', thumbnail: '', description: ''},
  {title: '단어 우월 효과', type: '영상', thumbnail: '', description: ''},
  {title: 'It’s my vibe', type: '영상', thumbnail: '', description: ''},
  {title: '자기소개 타이포그래피', type: '영상', thumbnail: '', description: ''},
  {title: '도쿄', type: '영상', thumbnail: '', description: ''},
  {title: '신명 카드뉴스', type: '그래픽', thumbnail: '', description: ''},
  {title: 'Look At You', type: '그래픽', thumbnail: '', description: ''},
  {title: 'Love poem', type: '그래픽', thumbnail: '', description: ''},
  {title: 'HALF MOON', type: '그래픽', thumbnail: '', description: ''},
  {title: 'THURS 6-25', type: '그래픽', thumbnail: '', description: ''},
  {title: 'Room', type: '3D', thumbnail: '', description: ''},
  {title: 'NETFLIX', type: '영상', thumbnail: '', description: ''},
  {title: '우체부', type: '일러스트', thumbnail: '', description: ''},
  {title: '할로윈', type: '일러스트', thumbnail: '', description: ''},
  {title: 'HOLYKNIGHT', type: '일러스트', thumbnail: '', description: ''},
  {title: 'Royal Archer', type: '일러스트', thumbnail: '', description: ''},
  {title: '도톤보리', type: '그래픽', thumbnail: '', description: ''},
  {title: '희극', type: '그래픽', thumbnail: '', description: ''},
  {title: '잉어', type: '그래픽', thumbnail: '', description: ''},
  {title: '에픽하이 로잘리오', type: '그래픽', thumbnail: '', description: ''},
  {title: '유튜브 꿀팁 인포그래픽', type: '그래픽', thumbnail: '', description: ''},
  {title: '이 번호로 전화해줘', type: '영상', thumbnail: '', description: ''},
  {title: '취향일지도', type: 'UI/UX', thumbnail: '', description: ''},
  {title: '11월의 초상화', type: '일러스트', thumbnail: '', description: ''},
  {title: '해질녘', type: '일러스트', thumbnail: '', description: ''},
  {title: '사신수 주작 화명', type: '일러스트', thumbnail: '', description: ''},
  {title: 'PPT 디자인', type: '그래픽', thumbnail: '', description: ''},
  {title: '호텔 델루나 만월당', type: '그래픽', thumbnail: '', description: ''},
  {title: '공익광고 포스터', type: '그래픽', thumbnail: '', description: ''},
  {title: '새벽 환상', type: '그래픽', thumbnail: '', description: ''},
  {title: '언택트 마케팅 카드뉴스', type: '그래픽', thumbnail: '', description: ''},
  {title: 'Streetlife', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'Stella', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'Travity', type: 'UI/UX', thumbnail: '', description: ''},
  {title: 'BUBLLY', type: 'UI/UX', thumbnail: '', description: ''},
  {title: '그 곳, 서울', type: '3D', thumbnail: '', description: ''},
  {title: 'Metro', type: '3D', thumbnail: '', description: ''},
  {title: 'Toss 모션그래픽', type: '영상', thumbnail: '', description: ''},
  {title: 'DAYFLY', type: '영상', thumbnail: '', description: ''},
]